### ISSUE TITLE
[Bug] Extension load error: Cannot read property 'usesCallbackServer' of undefined in index.ts

### ISSUE THREAD

**Issue by lighcen** [Sarrius/pi-multi-account#3]
### pi-multi-account version

1.3.0

### Pi Agent version

0.80.10

### Bug Description
When starting `pi`, the `pi-multi-account` extension fails to load with a `TypeError`.

### Error Output
```text
Error: Failed to load extension "~/.pi/agent/npm/node_modules/pi-multi-account/index.ts": Failed to load extension: undefined is not an object (evaluating '_oauth.openaiCodexOAuthProvider.usesCallbackServer')



### Steps to reproduce

Install pi-multi-account extension.

Run pi CLI.

See error on startup.

### /multi-account status output

```text

```

**Comment by Sarrius** [comment]
@lighcen thank you. Will check it

**Comment by Sarrius** [comment]
Fixed in **v1.14.0** (commit 9e9d115). Thanks for the report — and thanks to @lfoscari, whose PR #4 identified the second half of this.

Reproduced both causes before fixing, because there turned out to be two independent ones:

**1. pi-ai was only ever looked for *inside* the extension's own `node_modules`.**

The old resolution did exactly one probe:

```
<extension dir>/node_modules/@earendil-works/pi-ai/dist/oauth.js
```

That is the git-checkout layout. But `pi install npm:pi-multi-account` (and plain `npm i`) **hoists** pi-ai next to the package instead:

```
~/.pi/agent/npm/node_modules/pi-multi-account/index.ts
~/.pi/agent/npm/node_modules/@earendil-works/pi-ai/     <- one level up, never probed
```

So on every hoisted install the probe found nothing and the extension threw during load. Resolution now walks ancestor `node_modules` the way Node's own resolver does, and falls back to `require.resolve`.

**2. pi-ai 0.80 removed the runtime OAuth surface altogether.**

On 0.81/0.82, `dist/oauth.js` is literally:

```js
export {};
```

Types only. `getModel` moved to `dist/compat.js`, and the OAuth implementations moved behind provider factories with a new API — `anthropicProvider().auth.oauth` with `login(interaction)` / `refresh(credential)` instead of `loginAnthropic(callbacks)` / `refreshAnthropicToken(token)`. So even a *findable* pi-ai no longer had `openaiCodexOAuthProvider`, and reading `.usesCallbackServer` off it produced exactly the error in your report.

Both eras are now normalized behind one internal bridge, so the extension works on pi-ai 0.78 through 0.82+. That includes an adapter from Pi's legacy OAuth callbacks (`onAuth`/`onDeviceCode`/`onPrompt`/`onSelect`) to pi-ai's new `AuthInteraction` (`notify(event)`/`prompt(prompt)`) — which also fixes the `interaction.notify is not a function` crash during browser login.

**Loading is now non-fatal in every case.** If a pi-ai turns up that cannot be adapted at all, the extension still loads and every API-key account keeps rotating; only subscription login is unavailable, and you get a plain-language notice at session start instead of a cryptic property-of-undefined crash before the session even begins.

**Locked by tests** so it cannot silently come back (guarantee #18 in `GUARANTEES.md`). These run the real module resolution in a child process against fabricated pi-ai installs, since an in-process mock cannot check a resolution bug:

- `pi-ai is discovered when hoisted next to the package, not nested inside it`
- `hoisted install with a pre-0.80 pi-ai: extension loads and OAuth works`
- `hoisted install with pi-ai >= 0.80 (types-only dist/oauth.js): extension loads and OAuth is adapted`
- `no pi-ai at all: the extension still loads instead of dying at startup`

Each was verified failing before the fix and passing after.

Please update and let me know if anything is still off.

**Comment by Sarrius** [comment]
**v1.14.0 is now live on npm.**

```bash
pi install npm:pi-multi-account
```

Then fully restart Pi — a `/reload` is not always enough to pick up new extension code.

Thanks again for the report. If anything here is still not right after updating, please reopen this issue or open a new one with the output of `/multi-account log` — that log is the fastest way to see exactly what the failover decided and why.
